### PR TITLE
Add support for PHP 8.1, remove support for PHP 7.3

### PR DESCRIPTION
**Pull request by snapshotpl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Oof, we may need to polyfill this:

```
PHP Fatal error:  Trait 'Laminas\Db\Adapter\AdapterAwareTrait' not found in /github/workspace/vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 27
Fatal error: Trait 'Laminas\Db\Adapter\AdapterAwareTrait' not found in /github/workspace/vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 27
```

**Comment by snapshotpl** [comment]
Any idea why local machine runs psalm without issues?

**Comment by Ocramius** [comment]
@snapshotpl on PHP 7.3? :thinking:

**Comment by snapshotpl** [comment]
On 7.4

**Comment by snapshotpl** [comment]
Confirmed on 7.3

**Comment by Ocramius** [comment]
I like your pragmatic approach to the problem :+1:

**Review by Ocramius — APPROVED** [review]
Thanks @snapshotpl!

**Pull request merged**
