### PR TITLE
#27 Removed maximum and minimum values in path.

### LINKED ISSUE #27: Reason for maximum and minimum values
Hi!

Why there there are two parameters:

https://github.com/laminas-api-tools/api-tools-documentation-swagger/blob/29fc8ad2fdc241fc77edbda630862a095468c038/src/Service.php#L163-L171

```
'minimum'     => 0,
'maximum'     => 1,
```

I have URL path like that:

```
{
            "in": "path",
            "name": "service_point_id",
            "description": "URL parameter service_point_id",
            "type": "string",
            "required": true
}
```

If I pass service_point_id = 230419 Swagger UI does not allow it as it is not passing this minimum and maximum values.

### PR DESCRIPTION
**Pull request by tasselchof**
I removed default minimum and maximum parameters from the path.

Fixes #27

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
I don't have clear overview on whether `minimum` and `maximum` should be set or not, but the associated tests need to change together with the code change.

**Comment by tasselchof** [comment]
@Ocramius what should I do there? Psalm is failing because of external library.

Here:

https://github.com/laminas/laminas-validator/blob/329900ab7674c198e91e85b2e09080cdf493ce07/src/Db/AbstractDb.php#L29

A trait from laminas-db is used:

https://github.com/laminas/laminas-db/blob/feeb1ffe83793d33305950a48c0eb9e540976ef6/src/Adapter/AdapterAwareTrait.php

But validator is not requiring laminas-db (probably, because it can work without it for other cases).

**Comment by Ocramius** [comment]
@tasselchof I think that's out of the scope of your patch: the fact that `vimeo/psalm` crashes on a pre-existing issue is not caused by this change here  :)

**Comment by tasselchof** [comment]
@Ocramius okey, great. Should I do something else here?

**Comment by Ocramius** [comment]
Nope, just waiting for a review by another member of @laminas-api-tools/technical-steering-committee

**Comment by Ocramius** [comment]
@snapshotpl since you were freshly on this repo, are you able to help out with a review?

**Comment by snapshotpl** [comment]
Looks like `minimum` and `maximum` refers to integers, but here we have a string, so looks fine.

More https://swagger.io/docs/specification/describing-parameters/

**Review by snapshotpl — APPROVED** [review]

**Comment by Ocramius** [comment]
@tasselchof could you perhaps rebase this, so we can see if CI passes? I can't push the rebased changes to your fork, since it was created from an organization different from your account.

**Comment by tasselchof** [comment]
@Ocramius done.

**Review by Ocramius — APPROVED** [review]
Thanks @tasselchof!

**Pull request merged**
